/**
 * Project: ghana-regions
 * File: index
 * Created by pennycodes on 02/09/2023.
 * Copyright ghana-regions
 */

export interface Coordinates {
    latitude: number;
    longitude: number;
    full: string;
}

export interface Population {
    total: number;
    female: GenderPopulationMetrics;
    male: GenderPopulationMetrics;
    percentage: number;
    year: number;
    full: string;
    source: string;
}

export interface LandArea {
    total: number;
    unit: string;
    full: string;
    source: string;
}
export interface District {
    code: DISTRICT_CODES;
    label: string;
    capital: string;
  //  population: Population; TODO: not enough data
   // landArea: LandArea;
  //  coordinates: Coordinates;
    administrativeLevel: ADMINISTRATIVE_LEVELS;
    regionCode: REGION_CODES;
}

export interface GenderPopulationMetrics {
    total: number;
    percentage: number;
}
export interface Region {
    code: REGION_CODES;
    label: string;
    capital: string;
    population: Population;
    districts?: District[];
    landArea: LandArea;
}

export interface RegionsQuery {
    population?: boolean;
    landArea?: boolean;
    coordinates?: boolean;
    districts?: boolean;
}


export enum REGION_CODES {
    AHAFO_REGION = 'AR',
    ASHANTI_REGION = 'ASR',
    BONO_REGION = 'BR',
    BONO_EAST_REGION = 'BER',
    CENTRAL_REGION = 'CR',
    EASTERN_REGION = 'ER',
    GREATER_ACCRA_REGION = 'GAR',
    NORTHERN_REGION = 'NR',
    NORTH_EAST_REGION = 'NER',
    OTI_REGION = 'OR',
    SAVANNAH_REGION = 'SR',
    UPPER_EAST_REGION = 'UER',
    UPPER_WEST_REGION = 'UWR',
    VOLTA_REGION = 'VR',
    WESTERN_NORTH_REGION = 'WNR',
    WESTERN_REGION = 'WR'
}

export enum DISTRICT_CODES {
    ASUNAFO_NORTH_MUNICIPAL = 'ANM',
    ASUNAFO_SOUTH_DISTRICT = 'ASD',
    ASUTIFI_NORTH_DISTRICT = 'AND',
    ASUTIFI_SOUTH_DISTRICT = 'ATS',
    TANO_NORTH_MUNICIPAL = 'TNM',
    TANO_SOUTH_MUNICIPAL = 'TSM',
    ADANSI_ASOKWA_DISTRICT = 'AAD',
    ADANSI_NORTH_DISTRICT = 'ADD',
    ADANSI_SOUTH_DISTRICT = 'ADS',
    AFIGYA_KWABRE_NORTH_DISTRICT = 'AKN',
    AFIGYA_KWABRE_SOUTH_DISTRICT = 'AKS',
    AHAFO_ANO_NORTH_DISTRICT = 'AAN',
    AHAFO_ANO_SOUTH_EAST_DISTRICT = 'AAS',
    AHAFO_ANO_SOUTH_WEST_DISTRICT = 'AAW',
    AKROFUOM_DISTRICT = 'AKD',
    AMANSIE_CENTRAL_DISTRICT = 'ACD',
    AMANSIE_WEST_DISTRICT = 'AWD',
    AMANSIE_SOUTH_DISTRICT = 'AMS',
    ASANTE_AKIM_CENTRAL_MUNICIPAL = 'AACM',
    ASANTE_AKIM_NORTH_DISTRICT = 'AAND',
    ASANTE_AKIM_SOUTH_MUNICIPAL = 'AASM',
    ASOKORE_MAMPONG_MUNICIPAL = 'AMM',
    ASOKWA_MUNICIPAL = 'AM',
    ATWIMA_KWANWOMA_DISTRICT = 'ATKD',
    ATWIMA_MPONUA_DISTRICT = 'AMPD',
    ATWIMA_NWABIAGYA_MUNICIPAL = 'ANWM',
    ATWIMA_NWABIAGYA_NORTH_DISTRICT = 'ANWD',
    BEKWAI_MUNICIPAL = 'BM',
    BOSOME_FREHO_DISTRICT = 'BFD',
    BOSOMTWE_DISTRICT = 'BD',
    EJISU_MUNICIPAL = 'EM',
    EJURA_SEKYEDUMASE_MUNICIPAL = 'ESM',
    JUABEN_MUNICIPAL = 'JM',
    KUMASI_METROPOLITAN = 'KMA',
    KWABRE_EAST_DISTRICT = 'KED',
    KWADASO_MUNICIPAL = 'KM',
    MAMPONG_MUNICIPAL = 'MM',
    OBUASI_EAST_MUNICIPAL = 'OED',
    OBUASI_MUNICIPAL = 'OM',
    OFFINSO_NORTH_DISTRICT = 'OND',
    OFFINSO_MUNICIPAL = 'OM',
    OFORIKROM_MUNICIPAL = 'OFM',
    OLD_TAFO_MUNICIPAL = 'OTM',
    SEKYERE_AFRAM_PLAINS_DISTRICT = 'SAPD',
    SEKYERE_CENTRAL_DISTRICT = 'SCD',
    SEKYERE_EAST_DISTRICT = 'SED',
    SEKYERE_KUMAWU_DISTRICT = 'SKD',
    SEKYERE_SOUTH_DISTRICT = 'SSD',
    SUAME_MUNICIPAL = 'SM',
    BANDA_DISTRICT = 'BD',
    BEREKUM_EAST_MUNICIPAL = 'BEM',
    BEREKUM_WEST_DISTRICT = 'BWD',
    DORMAA_CENTRAL_MUNICIPAL = 'DCM',
    DORMAA_EAST_DISTRICT = 'DED',
    DORMAA_WEST_DISTRICT = 'DWD',
    JAMAN_NORTH_DISTRICT = 'JND',
    JAMAN_SOUTH_MUNICIPAL = 'JSM',
    SUNYANI_MUNICIPAL = 'SM',
    SUNYANI_WEST_DISTRICT = 'SWD',
    TAIN_DISTRICT = 'TD',
    WENCHI_MUNICIPAL = 'WM',
    ATEBUBU_AMANTIN_MUNICIPAL = 'AAM',
    KINTAMPO_NORTH_MUNICIPAL = 'KNM',
    KINTAMPO_SOUTH_DISTRICT = 'KSD',
    NKORANZA_NORTH_DISTRICT = 'NND',
    NKORANZA_SOUTH_MUNICIPAL = 'NSM',
    PRU_EAST_DISTRICT = 'PED',
    PRU_WEST_DISTRICT = 'PWD',
    SENE_EAST_DISTRICT = 'SED',
    SENE_WEST_DISTRICT = 'SWD',
    TECHIMAN_MUNICIPAL = 'TM',
    TECHIMAN_NORTH_DISTRICT = 'TND',
    ABURA_ASEBU_KWAMANKESE_DISTRICT = 'AAKD',
    AGONA_EAST_DISTRICT = 'AED',
    AGONA_WEST_MUNICIPAL = 'AWM',
    AJUMAKO_ENYAN_ESIAM_DISTRICT = 'AEED',
    ASIKUMA_ODOBEN_BRAKWA_DISTRICT = 'AOBD',
    ASSIN_CENTRAL_MUNICIPAL = 'ACM',
    ASSIN_NORTH_DISTRICT = 'AND',
    ASSIN_SOUTH_DISTRICT = 'ASD',
    AWUTU_SENYA_EAST_MUNICIPAL = 'ASEM',
    AWUTU_SENYA_WEST_DISTRICT = 'ASWD',
    CAPE_COAST_METROPOLITAN = 'CCM',
    EFFUTU_MUNICIPAL = 'EM',
    EKUMFI_DISTRICT = 'ED',
    GOMOA_EAST_DISTRICT = 'GED',
    GOMOA_WEST_DISTRICT = 'GWD',
    GOMOA_CENTRAL_DISTRICT = 'GCD',
    KOMENDA_EDINA_EGUAFO_ABIREM_MUNICIPAL = 'KEEAM',
    MFANTSIMAN_MUNICIPAL = 'MM',
    TWIFO_ATTI_MORKWA_DISTRICT = 'TAMD',
    TWIFO_HEMANG_LOWER_DENKYIRA_DISTRICT = 'THLDD',
    UPPER_DENKYIRA_EAST_MUNICIPAL = 'UDEM',
    UPPER_DENKYIRA_WEST_DISTRICT = 'UDWD',
    ABUAKWA_NORTH_MUNICIPAL = 'ANM',
    ABUAKWA_SOUTH_MUNICIPAL = 'ASM',
    ACHIASE_DISTRICT = 'AD',
    AKUAPEM_NORTH_MUNICIPAL = 'ANM',
    AKUAPEM_SOUTH_DISTRICT = 'ASD',
    AKYEMANSA_DISTRICT = 'AD',
    ASENE_MANSO_AKROSO_DISTRICT = 'AMAD',
    ASUOGYAMAN_DISTRICT = 'AD',
    ATIWA_EAST_DISTRICT = 'AED',
    ATIWA_WEST_DISTRICT = 'AWD',
    AYENSUANO_DISTRICT = 'AD',
    BIRIM_CENTRAL_MUNICIPAL = 'BCM',
    BIRIM_NORTH_DISTRICT = 'BND',
    BIRIM_SOUTH_DISTRICT = 'BSD',
    DENKYEMBUOR_DISTRICT = 'DD',
    FANTEAKWA_NORTH_DISTRICT = 'FND',
    FANTEAKWA_SOUTH_DISTRICT = 'FSD',
    KWAEBIBIREM_MUNICIPAL = 'KM',
    KWAHU_AFRAM_PLAINS_NORTH_DISTRICT = 'KAPND',
    KWAHU_AFRAM_PLAINS_SOUTH_DISTRICT = 'KAPSD',
    KWAHU_EAST_DISTRICT = 'KED',
    KWAHU_WEST_MUNICIPAL = 'KWM',
    KWAHU_SOUTH_DISTRICT = 'KSD',
    LOWER_MANYA_KROBO_MUNICIPAL = 'LMKM',
    NEW_JUABEN_NORTH_MUNICIPAL = 'NJNM',
    NEW_JUABEN_SOUTH_MUNICIPAL = 'NJSM',
    NSAWAM_ADOAGYIRI_MUNICIPAL = 'NAM',
    OKERE_DISTRICT = 'OD',
    SUHUM_MUNICIPAL = 'SM',
    UPPER_MANYA_KROBO_MUNICIPAL = 'UMKM',
    UPPER_WEST_AKIM_DISTRICT = 'UWAD',
    WEST_AKIM_MUNICIPAL = 'WAM',
    YILO_KROBO_MUNICIPAL = 'YKM',
    ABLEKUMA_CENTRAL_MUNICIPAL = 'ACM',
    ABLEKUMA_NORTH_MUNICIPAL = 'ANM',
    ABLEKUMA_WEST_MUNICIPAL = 'AWM',
    ACCRA_METROPOLITAN = 'AM',
    ADA_WEST_DISTRICT = 'AWD',
    ADA_EAST_DISTRICT = 'AED',
    ADENTA_MUNICIPAL = 'AM',
    ASHAIMAN_MUNICIPAL = 'AM',
    AYAWASO_CENTRAL_MUNICIPAL = 'ACM',
    AYAWASO_EAST_MUNICIPAL = 'AEM',
    AYAWASO_NORTH_MUNICIPAL = 'ANM',
    AYAWASO_WEST_MUNICIPAL = 'AWM',
    GA_CENTRAL_MUNICIPAL = 'GCM',
    GA_EAST_MUNICIPAL = 'GEM',
    GA_NORTH_MUNICIPAL = 'GNM',
    GA_SOUTH_MUNICIPAL = 'GSM',
    GA_WEST_MUNICIPAL = 'GWM',
    KORLEY_KLOTTEY_MUNICIPAL = 'KKM',
    KPONE_KATAMANSO_MUNICIPAL = 'KKM',
    KROWOR_MUNICIPAL = 'KM',
    LA_DADE_KOTOPON_MUNICIPAL = 'LDM',
    LA_NKWANTANANG_MADINA_MUNICIPAL = 'LNMM',
    LEDZOKUKU_MUNICIPAL = 'LKM',
    NINGO_PRAMPRAM_DISTRICT = 'NPD',
    OKAIKWEI_NORTH_MUNICIPAL = 'ONM',
    SHAI_OSU_DOKU_DISTRICT = 'SODD',
    TEMA_METROPOLITAN = 'TM',
    TEMA_WEST_MUNICIPAL = 'TWM',
    WEIJA_GBAWE_MUNICIPAL = 'WGM',
    GUSHEGU_MUNICIPAL = 'GM',
    KARAGA_DISTRICT = 'KD',
    KPANDAI_DISTRICT = 'KD',
    KUMBUNGU_DISTRICT = 'KD',
    MION_DISTRICT = 'MD',
    NANTON_DISTRICT = 'ND',
    NANUMBA_NORTH_MUNICIPAL = 'NNM',
    NANUMBA_SOUTH_DISTRICT = 'NSD',
    SABOBA_DISTRICT = 'SD',
    SAGNARIGU_MUNICIPAL = 'SM',
    SAVELUGU_MUNICIPAL = 'SM',
    TAMALE_METROPOLITAN = 'TM',
    TATALE_SANGULI_DISTRICT = 'TSD',
    TOLON_DISTRICT = 'TD',
    YENDI_MUNICIPAL = 'YM',
    ZABZUGU_DISTRICT = 'ZD',
    BUNKPURUGU_NYANKPANDURI_DISTRICT = 'BND',
    CHEREPONI_DISTRICT = 'CD',
    EAST_MAMPRUSI_MUNICIPAL = 'EMM',
    MAMPRUGU_MOAGDURI_DISTRICT = 'MMD',
    WEST_MAMPRUSI_MUNICIPAL = 'WMM',
    YUNYOO_NASUAN_DISTRICT = 'YND',
    BIAKOYE_DISTRICT = 'BD',
    JASIKAN_DISTRICT = 'JD',
    KADJEBI_DISTRICT = 'KD',
    KRACHI_EAST_MUNICIPAL = 'KEM',
    KRACHI_NCHUMURU_DISTRICT = 'KND',
    KRACHI_WEST_DISTRICT = 'KWD',
    NKWANTA_NORTH_DISTRICT = 'NND',
    NKWANTA_SOUTH_MUNICIPAL = 'NSM',
    BOLE_DISTRICT = 'BD',
    CENTRAL_GONJA_DISTRICT = 'CGD',
    EAST_GONJA_MUNICIPAL = 'EGM',
    NORTH_GONJA_DISTRICT = 'NGD',
    NORTH_EAST_GONJA_DISTRICT = 'NEGD',
    SAWLA_TUNA_KALBA_DISTRICT = 'STKD',
    WEST_GONJA_MUNICIPAL = 'WGM',
    BAWKU_MUNICIPAL = 'BM',
    BAWKU_WEST_DISTRICT = 'BWD',
    BINDURI_DISTRICT = 'BD',
    BOLGATANGA_EAST_DISTRICT = 'BED',
    BOLGATANGA_MUNICIPAL = 'BM',
    BONGO_DISTRICT = 'BD',
    BUILSA_NORTH_MUNICIPAL = 'BNM',
    BUILSA_SOUTH_DISTRICT = 'BSD',
    GARU_DISTRICT = 'GTD',
    KASSENA_NANKANA_MUNICIPAL = 'KNM',
    KASSENA_NANKANA_WEST_DISTRICT = 'KNWD',
    NABDAM_DISTRICT = 'ND',
    PUSIGA_DISTRICT = 'PD',
    TALENSI_DISTRICT = 'TND',
    TEMPANE_DISTRICT = 'TD',
    DAFFIAMA_BUSSIE_ISSA_DISTRICT = 'DBID',
    JIRAPA_MUNICIPAL = 'JM',
    LAMBUSSIE_KARNI_DISTRICT = 'LKD',
    LAWRA_MUNICIPAL = 'LM',
    NADOWLI_KALEO_DISTRICT = 'NKD',
    NANDOM_MUNICIPAL = 'NM',
    SISSALA_EAST_MUNICIPAL = 'SEM',
    SISSALA_WEST_DISTRICT = 'SWD',
    WA_EAST_DISTRICT = 'WED',
    WA_MUNICIPAL = 'WM',
    WA_WEST_DISTRICT = 'WWD',
    ADAKLU_DISTRICT = 'AD',
    AFADZATO_SOUTH_DISTRICT = 'ASD',
    AGOTIME_ZIOPE_DISTRICT = 'AZD',
    AKATSI_NORTH_DISTRICT = 'AND',
    AKATSI_SOUTH_DISTRICT = 'ASD',
    ANLOGA_DISTRICT = 'AD',
    CENTRAL_TONGU_DISTRICT = 'CTD',
    HO_MUNICIPAL = 'HM',
    HO_WEST_DISTRICT = 'HWD',
    HOHOE_MUNICIPAL = 'HM',
    KETA_MUNICIPAL = 'KM',
    KETU_NORTH_MUNICIPAL = 'KNM',
    KETU_SOUTH_MUNICIPAL = 'KSM',
    KPANDO_MUNICIPAL = 'KM',
    NORTH_DAYI_DISTRICT = 'NDD',
    NORTH_TONGU_DISTRICT = 'NTD',
    SOUTH_DAYI_DISTRICT = 'SDD',
    SOUTH_TONGU_DISTRICT = 'STD',
    AHANTA_WEST_MUNICIPAL = 'AWM',
    AMENFI_CENTRAL_DISTRICT = 'ACD',
    AMENFI_WEST_MUNICIPAL = 'AWM',
    EFFIA_KWESIMINTSIM_MUNICIPAL = 'EKM',
    ELLEMBELLE_DISTRICT = 'ED',
    JOMORO_MUNICIPAL = 'JM',
    MPOHOR_DISTRICT = 'MD',
    NZEMA_EAST_MUNICIPAL = 'NEM',
    PRESTEA_HUNI_VALLEY_MUNICIPAL = 'PHVM',
    SEKONDI_TAKORADI_METROPOLITAN = 'STM',
    SHAMA_DISTRICT = 'SD',
    TARKWA_NSUAYEM_MUNICIPAL = 'TNM',
    WASSA_AMENFI_EAST_MUNICIPAL = 'WAEM',
    WASSA_EAST_DISTRICT = 'WED',
    AOWIN_MUNICIPAL = 'AM',
    BIA_EAST_DISTRICT = 'BED',
    BIA_WEST_DISTRICT = 'BWD',
    BIBIANI_ANHWIASO_BEKWAI_MUNICIPAL = 'BABM',
    BODI_DISTRICT = 'BD',
    JUABOSO_DISTRICT = 'JD',
    SEFWI_AKONTOMBRA_DISTRICT = 'SAD',
    SEFWI_WIAWSO_MUNICIPAL = 'SWM',
    SUAMAN_DISTRICT = 'SD',
}

export enum ADMINISTRATIVE_LEVELS {
    MUNICIPAL = 'Municipal',
    DISTRICT = 'District',
    METROPOLITAN = 'Metropolitan',
}
